[Interface]
PrivateKey = +OVAcErUUgFyE50hafGqIV3zs6P+fTcVTCn2ieLZDHY=
Address = 10.0.0.3/24
ListenPort = 51820

[Peer]
# Fedora — Orchestrator
PublicKey = nG0naIx0RcZsybwaooX/ADoTloqy0m7V9gPwPmk9PmQ=
AllowedIPs = 10.0.0.1/32
Endpoint = 97.85.116.223:51820
PersistentKeepalive = 25

[Peer]
# Acer Nitro — L2
PublicKey = 7DRvBRYUTY0PYZQuLC2ZvZrWlhpck8ip8fdpSy1BKAU=
AllowedIPs = 10.0.0.2/32
Endpoint = 97.85.138.251:51820
PersistentKeepalive = 25

[Peer]
# HP Victus — L4
PublicKey = gA74Ss3XRKj7AmObIwzAQaICd579LIodeBPA5oh36RY=
AllowedIPs = 10.0.0.4/32
Endpoint = 97.85.155.44:51820
PersistentKeepalive = 25

[Peer]
# HP Pavilion — L5
PublicKey = gKUo3qN7HpweFWVBBlNWw0o+PkCmw6INH1t0eOcr/HU=
AllowedIPs = 10.0.0.5/32
Endpoint = 97.85.183.155:51820
PersistentKeepalive = 25
