[Interface]
PrivateKey = MNM9/gamlpS7jCjxs7qx+6+b0LtdTuMbNXKdI3PEjWc=
Address = 10.0.0.1/24
ListenPort = 51820

[Peer]
# Acer Nitro RTX 4050 — L2
PublicKey = 7DRvBRYUTY0PYZQuLC2ZvZrWlhpck8ip8fdpSy1BKAU=
AllowedIPs = 10.0.0.2/32
Endpoint = 97.85.138.251:51820
PersistentKeepalive = 25

[Peer]
# Lenovo LOQ RTX 3050 — L3
PublicKey = Ma53BNla1+Cd3xqh1pHyHHUwZJ2bpksi7cxrRsBbjik=
AllowedIPs = 10.0.0.3/32
Endpoint = 97.85.121.96:51820
PersistentKeepalive = 25

[Peer]
# HP Victus RTX 2050 — L4 + LLM
PublicKey = gA74Ss3XRKj7AmObIwzAQaICd579LIodeBPA5oh36RY=
AllowedIPs = 10.0.0.4/32
Endpoint = 97.85.155.44:51820
PersistentKeepalive = 25

[Peer]
# HP Pavilion GTX 1650 — L5 + Frontend
PublicKey = gKUo3qN7HpweFWVBBlNWw0o+PkCmw6INH1t0eOcr/HU=
AllowedIPs = 10.0.0.5/32
Endpoint = 97.85.183.155:51820
PersistentKeepalive = 25
