[Interface]
PrivateKey = +FBXHiNikY95jVD3s36FX5bYdz7Y1Mh07F+igf9w50A=
Address = 10.0.0.2/24
ListenPort = 51820

[Peer]
# Fedora — Orchestrator
PublicKey = nG0naIx0RcZsybwaooX/ADoTloqy0m7V9gPwPmk9PmQ=
AllowedIPs = 10.0.0.1/32
Endpoint = 97.85.116.223:51820
PersistentKeepalive = 25

[Peer]
# Lenovo LOQ — L3
PublicKey = Ma53BNla1+Cd3xqh1pHyHHUwZJ2bpksi7cxrRsBbjik=
AllowedIPs = 10.0.0.3/32
Endpoint = 97.85.121.96:51820
PersistentKeepalive = 25

[Peer]
# HP Victus — L4
PublicKey = gA74Ss3XRKj7AmObIwzAQaICd579LIodeBPA5oh36RY=
AllowedIPs = 10.0.0.4/32
Endpoint = 97.85.155.44:51820
PersistentKeepalive = 25

[Peer]
# HP Pavilion — L5
PublicKey = gKUo3qN7HpweFWVBBlNWw0o+PkCmw6INH1t0eOcr/HU=
AllowedIPs = 10.0.0.5/32
Endpoint = 97.85.183.155:51820
PersistentKeepalive = 25
