"""
IMMUNEX BiLSTM — Phase 3 Training Script (GPU Enforced, Class-Balanced)
Trains the Bidirectional LSTM on sequential 118D vectors generated by the GATv2
to map narrative trajectories predicting the 6-class MITRE Kill-Chain.

CLASS BALANCE FIX:
  ✅ Dedicated class 5 for Normal traffic — benign windows no longer mislabeled Recon (WRONG 2)
  ✅ Changed labeling from "max stage" → "most-frequent non-Normal stage" per window
  ✅ Rebalanced MITRE mapping to spread categories more evenly across 5 attack stages
  ✅ Overlapping sliding windows (stride=25) to generate 2x more training sequences
  ✅ Focal Loss to down-weight easy majority samples and focus on hard minority ones
  ✅ Class weights for remaining imbalance (SMOTE removed — wrong tool for sequences)
  ✅ Full GPU enforcement with AMP
  ✅ HMM priors learned from training data (saved to disk for hmm_predictor.py)
"""
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import AdamW
from torch.amp import GradScaler, autocast
from torch.utils.data import DataLoader, TensorDataset
from sklearn.metrics import f1_score, accuracy_score, classification_report
import pandas as pd
import numpy as np
import os
from collections import Counter

from graph_builder import create_hetero_graph_dataset
from gat_model import IMMUNEX_GATv2_Hetero
from bilstm_model import IMMUNEX_BiLSTM_Tracker

# =====================================================================
# REBALANCED MITRE 6-Class Kill-Chain Mapping
# WRONG 2 fix: Normal is now its own dedicated class (5) so the BiLSTM
# never confuses benign traffic with Reconnaissance.
# Class 5 acts as a suppression signal — the pipeline fires no alert
# when the predicted class is Normal.
# =====================================================================
BILSTM_STAGE_MAP = {
    'Normal': 5,                                         # Class 5: Benign (suppression)
    'Reconnaissance': 0, 'Analysis': 0,                 # Stage 0: Recon
    'Fuzzers': 1,                                        # Stage 1: Initial Access
    'Exploits': 2, 'DoS': 2,                            # Stage 2: Priv Esc
    'Generic': 3, 'Worms': 3,                           # Stage 3: Lat Move
    'Backdoor': 4, 'Backdoors': 4, 'Shellcode': 4       # Stage 4: Exfil
}


class FocalLoss(nn.Module):
    """
    Focal Loss — down-weights easy, well-classified samples and focuses
    the network's gradient signal on the hard, minority-class examples.
    Paper: "Focal Loss for Dense Object Detection" (Lin et al., 2017)
    """
    def __init__(self, weight=None, gamma=2.0, reduction='mean'):
        super().__init__()
        self.gamma = gamma
        self.weight = weight
        self.reduction = reduction

    def forward(self, input, target):
        ce_loss = F.cross_entropy(input, target, weight=self.weight, reduction='none')
        pt = torch.exp(-ce_loss)
        focal_loss = ((1 - pt) ** self.gamma) * ce_loss
        if self.reduction == 'mean':
            return focal_loss.mean()
        return focal_loss.sum()


def extract_window_label_frequency(stages_chunk: np.ndarray) -> int:
    """
    NEW LABELING STRATEGY: Instead of taking the MAX stage (which always
    overshadows stages 1 and 3), we take the MODE (most frequent) NON-NORMAL
    stage in the window (class 5 = Normal is treated as "no attack present").
    If a window contains 25 Fuzzers alerts and 2 Backdoor alerts, it is labeled
    InitAccess (1), not Exfil (4).

    WRONG 6 fix: A fully Normal window (all labels == 5) now returns 5 (Normal)
    instead of 0 (Reconnaissance). Returning 0 previously caused every benign
    window to be forcibly labeled as active recon.
    """
    NORMAL_CLASS = 5
    attack_labels = stages_chunk[stages_chunk != NORMAL_CLASS]
    if len(attack_labels) == 0:
        return NORMAL_CLASS  # All events are normal — suppress alert
    counts = Counter(attack_labels)
    return int(counts.most_common(1)[0][0])


# WRONG 3 fix: smote_oversample removed.
# SMOTE linearly interpolates between sequences of temporal GATv2 state vectors.
# Blending a DoS progression with a Backdoor progression creates a temporal
# narrative that never existed in reality — the BiLSTM memorizes physically
# impossible state transitions. FocalLoss + class weights are the correct tool
# for class imbalance on sequential data.


def train_bilstm_tracker(
    csv_path: str = "immunex_final_dataset.csv",
    gat_weights_path: str = "immunex_gatv2_phase2.pt",
    seq_length: int = 10,
    epochs: int = 50,
    lr: float = 0.001,
    save_path: str = "immunex_bilstm_phase3.pt",
    num_classes: int = 6  # WRONG 2 fix: 6 classes (0-4 attack + 5 Normal)
):
    # ------------------------------------------------------------------ GPU CHECK
    if not torch.cuda.is_available():
        raise EnvironmentError(
            "CRITICAL: CUDA GPU not detected!\n"
            "Run exactly: `py -3.14 train_bilstm.py`"
        )
    device = torch.device('cuda')
    torch.backends.cudnn.benchmark = True
    print(f"--- Launching IMMUNEX BiLSTM Training on {torch.cuda.get_device_name(0)} ---")
    print(f"    VRAM Available: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB")
    print(f"    Output classes: {num_classes} (0-4=attack stages, 5=Normal/Benign)")

    if not os.path.exists(csv_path) or not os.path.exists(gat_weights_path):
        print(f"[-] Missing: {csv_path} or {gat_weights_path}")
        return

    # 1. Load Dataset
    df = pd.read_csv(csv_path)
    events = df.to_dict('records')
    print(f"Loaded {len(df)} telemetry events.")

    # 2. Build stage labels for the ENTIRE dataset (vectorized)
    all_stages = df['attack_cat'].fillna('Normal').astype(str).str.strip().map(
        lambda x: BILSTM_STAGE_MAP.get(x, 0)
    ).values

    # 3. Extract 118D sequences via pre-trained GATv2 using OVERLAPPING windows
    #    Stride=25 instead of 50 → generates 2x more training data, critical for minority classes
    window_size = 50
    stride = 25
    print(f"\n[1/4] Building overlapping windows (size={window_size}, stride={stride})...")

    window_events = []
    window_labels = []
    for start in range(0, len(events) - window_size + 1, stride):
        chunk = events[start: start + window_size]
        chunk_stages = all_stages[start: start + window_size]
        label = extract_window_label_frequency(chunk_stages)
        window_events.append(chunk)
        window_labels.append(label)

    print(f" > Built {len(window_events)} overlapping windows.")
    print(f" > Window label distribution: {dict(Counter(window_labels))}")

    # Build PyG graphs from the overlapping windows
    print("\n[2/4] Feeding windows through GATv2 to generate 118D vectors...")
    from graph_builder import construct_heterogeneous_graph

    # Load GATv2
    sample_graph = construct_heterogeneous_graph(window_events[0])
    gat_model = IMMUNEX_GATv2_Hetero(
        metadata=sample_graph.metadata(), hidden_channels=128, num_classes=4, out_dim=118, heads=8
    ).to(device)
    gat_model.load_state_dict(torch.load(gat_weights_path, map_location=device, weights_only=True))
    gat_model.eval()

    chronological_vectors = []
    chronological_labels = []

    with torch.no_grad():
        for i, (win_events, win_label) in enumerate(zip(window_events, window_labels)):
            graph_data = construct_heterogeneous_graph(win_events).to(device, non_blocking=True)
            alert_batch = torch.zeros(graph_data['alert'].num_nodes, dtype=torch.long, device=device)

            with autocast('cuda'):
                _, state_vector, _ = gat_model(graph_data.x_dict, graph_data.edge_index_dict, alert_batch)

            chronological_vectors.append(state_vector.cpu().float().numpy()[0])
            chronological_labels.append(win_label)

            if (i + 1) % 500 == 0:
                print(f"   Processed {i+1}/{len(window_events)} windows...")

    print(f" > Extracted {len(chronological_vectors)} sequential 118D state vectors.")

    # 4. Compile Rolling Sequence Dataset
    print(f"\n[3/4] Compiling BiLSTM sequences (length={seq_length}) + SMOTE oversampling...")
    X_seq, Y_seq = [], []
    for i in range(len(chronological_vectors) - seq_length):
        X_seq.append(chronological_vectors[i: i + seq_length])
        Y_seq.append(chronological_labels[i + seq_length - 1])

    if len(X_seq) == 0:
        print("[-] Not enough windows for sequences.")
        return

    X_arr = np.array(X_seq)
    Y_arr = np.array(Y_seq)

    # WRONG 3 fix: SMOTE removed. It interpolates sequential temporal vectors from different
    # attack progressions (e.g. DoS + Backdoor) creating physically impossible temporal
    # narratives. FocalLoss + inverse class weights are the right tool for sequence imbalance.
    print(f" > Sequence label distribution: {dict(Counter(Y_arr))}")

    X_tensor = torch.tensor(X_arr, dtype=torch.float32)
    Y_tensor = torch.tensor(Y_arr, dtype=torch.long)

    # Compute inverse-frequency class weights across all num_classes classes
    unique, counts = np.unique(Y_arr, return_counts=True)
    class_weights = np.ones(num_classes, dtype=np.float32)
    for cls, count in zip(unique, counts):
        if 0 <= cls < num_classes:
            class_weights[cls] = max(1.0, len(Y_arr) / (count * num_classes))
    weights_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)

    loader = DataLoader(
        TensorDataset(X_tensor, Y_tensor),
        batch_size=64, shuffle=True, pin_memory=True, num_workers=0
    )

    # 5. Train BiLSTM with Focal Loss + AMP
    print(f"\n[4/4] Training BiLSTM with Focal Loss (gamma=2.0) for {epochs} epochs ({num_classes} classes)...")
    bilstm = IMMUNEX_BiLSTM_Tracker(input_dim=118, hidden_dim=128, num_layers=2, num_classes=num_classes).to(device)
    optimizer = AdamW(bilstm.parameters(), lr=lr, weight_decay=1e-4)
    criterion = FocalLoss(weight=weights_tensor, gamma=2.0)
    scaler = GradScaler('cuda')
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    best_f1 = 0.0

    for epoch in range(1, epochs + 1):
        bilstm.train()
        total_loss = 0
        all_preds, all_labels = [], []

        for batch_x, batch_y in loader:
            batch_x = batch_x.to(device, non_blocking=True)
            batch_y = batch_y.to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)

            with autocast('cuda'):
                logits = bilstm(batch_x)
                loss = criterion(logits, batch_y)

            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(bilstm.parameters(), max_norm=1.0)
            scaler.step(optimizer)
            scaler.update()

            total_loss += loss.item()
            preds = logits.argmax(dim=1)
            all_preds.extend(preds.detach().cpu().numpy())
            all_labels.extend(batch_y.detach().cpu().numpy())

        scheduler.step()

        epoch_acc = accuracy_score(all_labels, all_preds)
        epoch_f1 = f1_score(all_labels, all_preds, average='macro', zero_division=0)

        if epoch % 5 == 0 or epoch == 1:
            vram_used = torch.cuda.memory_reserved(0) / 1024**3
            print(f"Epoch {epoch:03d}/{epochs} | Loss: {total_loss/len(loader):.4f} | "
                  f"Acc: {epoch_acc*100:.2f}% | F1: {epoch_f1*100:.2f}% | VRAM: {vram_used:.2f}GB")

        if epoch_f1 > best_f1:
            best_f1 = epoch_f1
            torch.save(bilstm.state_dict(), save_path)

    print("\n--- Training Complete ---")
    print(f"Saved: {save_path} (Best Macro F1: {best_f1*100:.2f}%)")
    target_names = ['Recon(0)', 'InitAccess(1)', 'PrivEsc(2)', 'LatMove(3)', 'Exfil(4)', 'Normal(5)']
    valid_names = [target_names[i] for i in range(num_classes) if i in unique]
    print("\nNarrative Classification Report:")
    print(classification_report(all_labels, all_preds, target_names=valid_names, zero_division=0))

    # ================================================================
    # HMM REDESIGN — Tier 4: Learn transition priors from real data
    # ================================================================
    # Filters to only ATTACK labels (0-4) for the HMM — the HMM models
    # adversarial stage transitions, not Normal → Normal self-loops.
    import json as _json

    def learn_hmm_priors(labels: list, n_stages: int = 5,
                         matrix_path: str = "hmm_transition_counts.npy",
                         dwell_path: str = "hmm_dwell_times.json",
                         window_seconds: int = 30):
        """
        Learns the HMM transition matrix and per-stage dwell times
        from the actual BiLSTM training sequence labels.

        Saves two artifacts that hmm_predictor.py reads on startup:
          hmm_transition_counts.npy  — (5,5) count matrix with Laplace smoothing
          hmm_dwell_times.json       — mean/std dwell time per stage in seconds
        """
        NORMAL_CLASS = 5
        # Only keep attack-stage labels for the transition matrix
        attack_labels = [l for l in labels if l != NORMAL_CLASS]
        arr = np.array(attack_labels)

        # Laplace smoothing: start with 1 count per cell (no impossible transitions)
        counts = np.ones((n_stages, n_stages), dtype=np.float64)
        for prev, curr in zip(arr[:-1], arr[1:]):
            if 0 <= prev < n_stages and 0 <= curr < n_stages:
                counts[prev, curr] += 1

        np.save(matrix_path, counts)
        print(f"\n[HMM] Learned transition matrix saved to {matrix_path}")
        print(counts.astype(int))

        # Dwell time: how many consecutive windows does each stage persist?
        from collections import defaultdict
        runs: dict = defaultdict(list)
        if len(arr) > 0:
            current_stage, run_len = arr[0], 1
            for label in arr[1:]:
                if label == current_stage:
                    run_len += 1
                else:
                    runs[int(current_stage)].append(run_len * window_seconds)
                    current_stage, run_len = label, 1
            runs[int(current_stage)].append(run_len * window_seconds)

        dwell: dict = {}
        for stage in range(n_stages):
            times = runs.get(stage, [window_seconds])
            dwell[stage] = {
                "mean_seconds": int(np.mean(times)),
                "std_seconds":  int(np.std(times)) if len(times) > 1 else 0,
                "sample_count": len(times)
            }

        with open(dwell_path, "w") as f:
            _json.dump(dwell, f, indent=2)
        print(f"[HMM] Dwell times saved to {dwell_path}")
        print(_json.dumps(dwell, indent=2))

    learn_hmm_priors(chronological_labels)

if __name__ == "__main__":
    train_bilstm_tracker()
