version: '3.8'

services:
  immunex_db:
    image: pgvector/pgvector:pg16
    container_name: immunex_pgvector
    restart: always
    environment:
      POSTGRES_USER: immunex_admin
      POSTGRES_PASSWORD: super_secure_password
      POSTGRES_DB: immunex_threat_memory
    ports:
      - "5432:5432"
    volumes:
      - pgdata_immunex:/var/lib/postgresql/data

volumes:
  pgdata_immunex: